openapi: 3.0.0
info:
  title: Especificação - criação da conta de usuário
  description: Especificação - criação da conta de usuário
  contact:
    email: leo.sena777@gmail.com
  version: 1.0.0
servers:
- url: /
security:
- aplication:
  - read
  - write
paths:
  /accounts:
    get:
      summary: Recuperar todas as contas
      parameters:
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: todo...
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Token inválido, inexistente ou expirado
        "500":
          description: Erro no servido
    post:
      summary: Cria uma nova conta
      parameters:
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: todo...
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "201":
          description: Criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Token inválido, inexistente ou expirado
        "404":
          description: Account {id} não encontrado
        "500":
          description: Erro no servido
  /accounts/{id}:
    get:
      summary: Recupera uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id de indentificação da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: todo...
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Token inválido, inexistente ou expirado
        "500":
          description: Erro no servido
    put:
      summary: Atualiza uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id de indentificação da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: todo...
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_request'
        required: true
      responses:
        "202":
          description: Aceito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Token inválido, inexistente ou expirado
        "500":
          description: Erro no servido
    delete:
      summary: Exclui uma conta de usuário pelo id
      parameters:
      - name: id
        in: path
        description: id de indentificação da conta do usuário
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: token
        in: header
        description: Token JWT no header
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
            format: string
        example: todo...
      responses:
        "204":
          description: Sem conteúdo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        "400":
          description: Dados request enviados incorretos
        "401":
          description: Token inválido, inexistente ou expirado
        "500":
          description: Erro no servido
components:
  schemas:
    body_response:
      required:
      - dateBirth
      - email
      - firstName
      - gender
      - id
      - lastName
      - phoneNumber
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: First
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: email@email.com
        phoneNumber:
          type: string
          example: 00-0000-0000
        dateBirth:
          type: string
          format: date
        gender:
          type: string
          example: M
          enum:
          - M
          - F
    body_request:
      required:
      - dateBirth
      - email
      - firstName
      - gender
      - lastName
      - password
      - phoneNumber
      type: object
      properties:
        firstName:
          type: string
          example: First
        lastName:
          type: string
          example: Last
        email:
          type: string
          format: email
          example: email@email.com
        phoneNumber:
          type: string
          example: 00-0000-0000
        password:
          type: string
          format: password
          example: "123456"
        dateBirth:
          type: string
          format: date
        gender:
          type: string
          example: M
          enum:
          - M
          - F
